In [4]:
# Task 1. 
# • Create a TensorFlow tensor with random float values. Calculate the sum, mean, and   maximum of the tensor. Hint: Use tf.reduce_sum(), tf.reduce_mean(), tf.reduce_max(). 

import tensorflow as tf


random_tensor = tf.random.uniform(shape=[5], minval=0, maxval=1)


sum_value = tf.reduce_sum(random_tensor)
mean_value = tf.reduce_mean(random_tensor)
max_value = tf.reduce_max(random_tensor)

# Print results
print("Random Tensor:", random_tensor.numpy())
print("Sum:", sum_value.numpy())
print("Mean:", mean_value.numpy())
print("Max:", max_value.numpy())


Random Tensor: [0.3224473  0.8626516  0.2627145  0.48103607 0.96519804]
Sum: 2.8940475
Mean: 0.5788095
Max: 0.96519804


In [6]:
# •  Create a 3D TensorFlow tensor. Access and print a specific element, a 2D slice, and a 1D  slice.    Hint: Use standard Python indexing and slicing syntax.
import tensorflow as tf
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],  
    [[5, 6], [7, 8]],  
    [[9, 10], [11, 12]] 
])

# Access a specific element (2nd matrix, 1st row, 2nd column)
specific_element = tensor_3d[1, 0, 1]  

# Access a 2D slice (Get entire 2nd matrix)
slice_2d = tensor_3d[1]

# Access a 1D slice (Get 1st row of the 3rd matrix)
slice_1d = tensor_3d[2, 0]  


print("3D Tensor:\n", tensor_3d.numpy())
print("Specific Element:", specific_element.numpy())
print("2D Slice:\n", slice_2d.numpy())
print("1D Slice:", slice_1d.numpy())

3D Tensor:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Specific Element: 6
2D Slice:
 [[5 6]
 [7 8]]
1D Slice: [ 9 10]


In [9]:
# TASK 2 
tensor1 = tf.constant([10, 20, 30])
tensor2 = tf.constant([5, 10, 15])

def tensor_operations(tensor1, tensor2):
  
    return {
        "addition": tensor1 + tensor2,
        "subtraction": tensor1 - tensor2,
        "multiplication": tensor1 * tensor2,
        "division": tensor1 / tensor2
    }


results = tensor_operations(tensor1, tensor2)


for key, value in results.items():
    print(f"{key.capitalize()}: {value.numpy()}")


Addition: [15 30 45]
Subtraction: [ 5 10 15]
Multiplication: [ 50 200 450]
Division: [2. 2. 2.]


In [12]:
# Task 3.
# 1. Create & Sort a NumPy Array
import numpy as np

random_array = np.random.rand(5)

# Sort in ascending and descending order
sorted_asc = np.sort(random_array)
sorted_desc = np.sort(random_array)[::-1]

print("Original Array:", random_array)
print("Sorted Ascending:", sorted_asc)
print("Sorted Descending:", sorted_desc)


Original Array: [0.46489735 0.96536741 0.54152111 0.90155251 0.9365818 ]
Sorted Ascending: [0.46489735 0.54152111 0.90155251 0.9365818  0.96536741]
Sorted Descending: [0.96536741 0.9365818  0.90155251 0.54152111 0.46489735]


In [14]:
# 2. Create a 2x2 Matrix, Find Transpose & Inverse
# Create a 2x2 NumPy matrix
matrix = np.array([[4, 7], [2, 6]])

# Transpose the matrix
transpose_matrix = np.transpose(matrix)

# Inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:\n", matrix)
print("Transpose:\n", transpose_matrix)
print("Inverse:\n", inverse_matrix)


Original Matrix:
 [[4 7]
 [2 6]]
Transpose:
 [[4 2]
 [7 6]]
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [16]:
# 3. Perform Row Sum, Column Mean, & Standard Deviation
# Create a 2D NumPy array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Sum of each row
row_sums = np.sum(array_2d, axis=1)

# Mean of each column
column_means = np.mean(array_2d, axis=0)

# Standard deviation of entire array
std_dev = np.std(array_2d)

print("2D Array:\n", array_2d)
print("Sum of Each Row:", row_sums)
print("Mean of Each Column:", column_means)
print("Standard Deviation of Entire Array:", std_dev)


2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Sum of Each Row: [ 60 150 240]
Mean of Each Column: [40. 50. 60.]
Standard Deviation of Entire Array: 25.81988897471611
